### ISSUE TITLE
Assessment Review

### ISSUE THREAD

**Issue by rwarbelow** [AnnaGoodwin/mod_0_skills#1]
**Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub**

- [x] Did you name and structure your directories and files correctly?
- [x] Did you make one initial commit?
- [x] Did you push your initial commit to Github?

**Part II: Top Down Design**

- [x] Did you break down larger processes into multiple smaller layers?
- [x] Did you add and commit your changes with a properly formatted commit message?
- [x] Did you push your changes to Github?

**Part III: Classes in a System** 

- [x] Did you structure and name your directories and files correctly?
- [ ] Did you correctly categorize attributes and methods for each class?

Comments: Your `Waiter` class is great! For the other two classes, check your attributes. For example, a better attribute for `Chef` would be `HatColor` (instead of `WhiteHat`). 

The `Bathroom` class is a little trickier. Here's what I might do:

```
Bathroom

Attributes:
Toilets (array)
Sinks (array)
LightsOn (boolean)
Gender (string)

Methods:
ToggleLights
RunWater
RunDryer
```

I would remove the `CleanHands` and `DryHands` methods since those are actions of a person, not a bathroom (a bathroom can't clean its hands). 

- [x] Did you correctly identify data types of attributes for each class?
- [x] Did you add and commit each set of changes separately with a properly formatted commit message?
- [x] Did you push your changes to Github?

**Assessment Results**
- [x] Pass
- [ ] Conditional pass
- [ ] Fail with recommend for Mod 0 repeat
